controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

lexik_jwt_authentication_login_check:
  path: /api/login_check
  controller: lexik_jwt_authentication.controller.login
  methods: [POST]